import ArtistPage from '../components/ArtistPage.jsx'

const DATA = {
  id: 'roupa-nova',
  name: 'Roupa Nova',
  fullName: 'Cleberson, Serginho, Ricardo, Kiko, Nando, Feghali',
  born: '1980 · Rio de Janeiro, RJ',
  era: 'Pop romântico brasileiro',
  category: 'R&B / Soul',
  bio: 'Banda que definiu o pop romântico brasileiro — com forte influência do soul, R&B e black music americana. Vocais empilhados, arranjos vocais à la Earth Wind & Fire, harmonias com 7ª, 9ª e 13ª. "Whisky a Go-Go", "Dona", "A Viagem" são clássicos absolutos.',
  genres: ['Pop romântico', 'Soul', 'R&B', 'AOR'],
  images: [
    { src: '/images/roupanova.jpg',  label: 'O sexteto clássico' },
    { src: '/images/roupanova2.jpg', label: 'Anos de hits' },
    { src: '/images/roupanova3.jpg', label: 'Era contemporânea' },
  ],
  color: '#ec4899',
  bgFrom: '#831843',
  bgTo: '#4a0e2c',
  trademarks: [
    'Acordes com 7ª maior e 9ª (heritage soul/jazz)',
    'Vocais empilhados em terças e sextas (estilo Stylistics, Earth Wind & Fire)',
    'Modulações ascendentes no refrão final (recurso AOR clássico)',
    'Bridge harmonicamente sofisticada — entrega "jazzy" dentro do pop',
  ],
  songs: [
    {
      id: 'dona', title: 'Dona', year: 1983, album: 'Roupa Nova',
      key: 'D', accent: '#ec4899',
      description: 'Balada romântica que abriu caminho para o pop-soul brasileiro. Harmonia em ré maior com acordes maj7 e bridge surpreendentemente jazzística para o pop dos anos 80.',
      composition: 'Composta por Cleberson Horsth (pianista do grupo). A música foi rejeitada por 3 gravadoras antes de virar hit — "muito jazz pra ser pop, muito pop pra ser jazz". O recurso composicional decisivo: as backing vocals fazem terças PARALELAS em quase toda a canção, mas no refrão fazem SEXTAS — abertura sonora que dá o "salto" de intensidade sem mudar o volume. Esse trick vem direto do Earth Wind & Fire e dos Stylistics. A bridge é puro jazz: ii-V-I em sol maior antes de voltar pra ré.',
      sections: [
        { name: 'Verso', progression: ['Dmaj7', 'Bm7', 'Em7', 'A7'],
          analysis: 'IM7 – vi7 – ii7 – V7. Cadência ii-V-I clássica do jazz, mas vestida com timbres pop. Os maj7 e min7 dão o brilho soul.' },
        { name: 'Pré-refrão', progression: ['Gmaj7', 'F#m7', 'Em7', 'A7'],
          analysis: 'IVM7 – iii7 – ii7 – V7. Descida diatônica clássica do soul — exatamente o tipo de movimento que aparece em hits do Marvin Gaye.' },
        { name: 'Refrão', progression: ['D', 'Bm', 'G', 'A'],
          analysis: 'I – vi – IV – V. Simplifica no refrão para que o público cante. Mas as backing vocals continuam fazendo as tensões (9, 11) — recurso típico do R&B.' },
      ],
      chords: [
        { root: 'D',  key: 'maj7', label: 'Dmaj7',  role: 'IM7 — tônica brilhante' },
        { root: 'D',  key: 'maj',  label: 'D',      role: 'I' },
        { root: 'B',  key: 'min7', label: 'Bm7',    role: 'vi7' },
        { root: 'B',  key: 'min',  label: 'Bm',     role: 'vi' },
        { root: 'E',  key: 'min7', label: 'Em7',    role: 'ii7' },
        { root: 'A',  key: '7',    label: 'A7',     role: 'V7' },
        { root: 'A',  key: 'maj',  label: 'A',      role: 'V' },
        { root: 'G',  key: 'maj7', label: 'Gmaj7',  role: 'IVM7' },
        { root: 'G',  key: 'maj',  label: 'G',      role: 'IV' },
        { root: 'F#', key: 'min7', label: 'F#m7',   role: 'iii7' },
      ],
    },
    {
      id: 'whisky-a-go-go', title: 'Whisky a Go-Go', year: 1980, album: 'Roupa Nova',
      key: 'Am', accent: '#f43f5e',
      description: 'O primeiro hit da banda. Disco-funk com letra de festa. Harmonia menor com groove constante na guitarra e baixo — base perfeita para os vocais empilhados.',
      composition: 'Lançada em 1980, exatamente quando a febre disco morria nos EUA e o Roupa Nova trouxe o gênero pro Brasil sem complexo. O título cita uma boate famosa de Los Angeles — referência consciente ao disco californiano. Recurso composicional: o baixo usa o "octave bass" (pulando entre tônica e oitava em colcheia) — assinatura sonora do Bee Gees e Chic. Os 6 integrantes cantam juntos em UNÍSSONO no refrão (não em harmonias) — coral massivo que cria peso bruto, recurso usado pelo Earth Wind & Fire em "September".',
      sections: [
        { name: 'Verso (groove)', progression: ['Am7', 'Dm7', 'G7', 'Cmaj7'],
          analysis: 'i7 – iv7 – bVII7 – bIIIM7. Movimento ascendente por quartas — fórmula clássica do disco e do funk. A guitarra faz síncopes cravadas no contratempo.' },
        { name: 'Ponte', progression: ['Fmaj7', 'E7', 'Am7', 'Dm7'],
          analysis: 'bVIM7 – V7 – i7 – iv7. O E7 (V7) com a 3ª maior cria a tensão "blueada" que prepara o retorno à tônica menor.' },
        { name: 'Refrão', progression: ['Am', 'F', 'G', 'Am'],
          analysis: 'i – bVI – bVII – i. Cadência menor de rock/funk. Sem 7ª aqui — punch direto pra dançar.' },
      ],
      chords: [
        { root: 'A',  key: 'min7', label: 'Am7',    role: 'i7 — tônica' },
        { root: 'A',  key: 'min',  label: 'Am',     role: 'i' },
        { root: 'D',  key: 'min7', label: 'Dm7',    role: 'iv7' },
        { root: 'G',  key: '7',    label: 'G7',     role: 'bVII7' },
        { root: 'G',  key: 'maj',  label: 'G',      role: 'bVII' },
        { root: 'C',  key: 'maj7', label: 'Cmaj7',  role: 'bIIIM7 — relativo' },
        { root: 'F',  key: 'maj7', label: 'Fmaj7',  role: 'bVIM7' },
        { root: 'F',  key: 'maj',  label: 'F',      role: 'bVI' },
        { root: 'E',  key: '7',    label: 'E7',     role: 'V7' },
      ],
    },
    {
      id: 'a-viagem', title: 'A Viagem', year: 1984, album: 'Lá Vou Eu',
      key: 'G', accent: '#fb7185',
      description: 'Balada épica com modulação ascendente no refrão final (truque do AOR/yacht rock). Harmonia em sol maior com 9ª e 13ª nos acordes-chave.',
      composition: 'Tema do longa "A Viagem" (1994) — daí a aura cinematográfica. Composta por Cleberson Horsth e Paulo Sérgio Valle (irmão de Marcos Valle). A modulação para Db maior no refrão final é decisão consciente de inflar o peso emocional sem mudar a melodia. Esse "key change up a half step" é fórmula consagrada do AOR americano (Foreigner "I Want to Know What Love Is", Whitney Houston "I Will Always Love You"). Roupa Nova foi a primeira banda brasileira a usar esse recurso com naturalidade.',
      sections: [
        { name: 'Verso', progression: ['G', 'Em7', 'C', 'D'],
          analysis: 'I – vi7 – IV – V. A 7ª no Em7 acrescenta a "doçura soul" — sem ela seria pop genérico, com ela vira pop sofisticado.' },
        { name: 'Pré-refrão', progression: ['Am7', 'D7', 'Bm7', 'E7'],
          analysis: 'ii7 – V7 – iii7 – V7/vi. O E7 (dominante secundário) prepara o vi (Am) mas surpreendentemente vai pro refrão em G.' },
        { name: 'Refrão (com modulação no final)', progression: ['G', 'D', 'Em7', 'C', 'Ab'],
          analysis: 'I – V – vi7 – IV – ... e o Ab é o V do novo tom (Db)! Modulação ascendente para Db maior — clássico recurso do AOR para "subir" emocionalmente no refrão final.' },
      ],
      chords: [
        { root: 'G',  key: 'maj',  label: 'G',     role: 'I — tônica' },
        { root: 'E',  key: 'min7', label: 'Em7',   role: 'vi7' },
        { root: 'C',  key: 'maj',  label: 'C',     role: 'IV' },
        { root: 'D',  key: 'maj',  label: 'D',     role: 'V' },
        { root: 'D',  key: '7',    label: 'D7',    role: 'V7' },
        { root: 'A',  key: 'min7', label: 'Am7',   role: 'ii7' },
        { root: 'B',  key: 'min7', label: 'Bm7',   role: 'iii7' },
        { root: 'E',  key: '7',    label: 'E7',    role: 'V7/vi — dominante secundário' },
        { root: 'Ab', key: 'maj',  label: 'Ab',    role: 'V do novo tom (modulação)' },
      ],
    },
  ],
  lessons: [
    { title: 'maj7 e min7 são a marca do soul',
      text: 'Roupa Nova quase nunca toca um acorde "puro" sem 7ª. Comparado ao pop de mesma época que usa só tríades, isso eleva o som imediatamente para o território R&B.' },
    { title: 'A modulação ascendente é o "clímax barato"',
      text: 'Subir 1/2 ou 1 tom no último refrão é truque velho do AOR — mas funciona toda vez. Roupa Nova usa esse recurso com gosto e cria momentos épicos baratos (mas eficazes).' },
    { title: 'Cadeias ii–V–I em qualquer estilo',
      text: 'Mesmo no pop romântico, os Roupa Nova trazem cadências jazz (ii–V–I) que dão a profundidade harmônica. É o "ingrediente secreto" do soul/R&B brasileiro.' },
  ],
}

export default function RoupaNova() {
  return <ArtistPage data={DATA} />
}
